version: 2.1
orbs:
  android: circleci/android@2.2.0
  gradle: circleci/gradle@3.0.0



jobs:
  machine-build:
    parameters:
      resource-class:
        type: string
        default: "medium"
    machine:
      image: android:2023.09.1
    resource_class: << parameters.resource-class >>
    steps:
      - checkout
      - run: ./gradlew build
      - android/start-emulator-and-run-tests:
          pre-run-tests-steps:
            - run: echo "beginning tests"
          test-command: flutter test
          pre-emulator-wait-steps:
            - run: echo "waiting for emulator"
          post-emulator-wait-steps:
            - run: echo "emulator running"
          post-emulator-launch-assemble-command: './gradlew test'
          post-run-tests-steps: 
            - run: echo "run test done"
            - run: mkdir testdata
            - run: adb pull storage .
          additional-avd-args: "-d pixel_3a -c 1G"
          additional-emulator-args: "-memory 4096 -cores 3 -writable-system"
          avd-name: 'testing'
          system-image: system-images;android-34;google_apis_playstore;x86_64

  docker-build:
    parameters:
      resource-class:
        type: string
        default: "medium"
    docker:
      - image: cimg/android:2023.09.1
    resource_class: << parameters.resource-class >>
    steps:
      - checkout
      - run: ./gradlew build
      - android/start-emulator-and-run-tests:
          pre-run-tests-steps:
            - run: echo "beginning tests"
          test-command: flutter test
          pre-emulator-wait-steps:
            - run: echo "waiting for emulator"
          post-emulator-wait-steps:
            - run: echo "emulator running"
          post-emulator-launch-assemble-command: './gradlew test'
          post-run-tests-steps: 
            - run: echo "run test done"
            - run: mkdir testdata
            - run: adb pull storage .
          additional-avd-args: "-d pixel_3a -c 1G"
          additional-emulator-args: "-memory 4096 -cores 3 -writable-system"
          avd-name: 'testing'
          system-image: system-images;android-34;google_apis_playstore;x86_64

workflows:
  docker-and-machine-build:
    jobs:
      - machine-build:
          matrix:
            parameters:
              resource-class: ["medium", "large", "xlarge", "2xlarge"]
      - docker-build:
          matrix:
            parameters:
              resource-class: ["small", "medium", "medium+", "large", "xlarge", "2xlarge"]